### ISSUE TITLE
几个疑问想请教

### ISSUE THREAD

**Issue by MokouTyan** [Moyuyanli/HuYanSession#1]
作者你好，该插件能不能实现
1.发送聊天记录，类似于下图
![image](https://user-images.githubusercontent.com/40456395/175876773-09ae3ef8-40ce-40d4-a11c-c0b4f9426fbb.png)
2.可不可以将学习的东西应用在多个群中（给群分组，给这个组的机器人相同配置
原因：将机器人放在学校的几个新生群做答疑用，Q群管家有要修改的话需要一个一个群改

**Comment by Moyuyanli** [comment]
你好，关于第一个问题，技术上可以实现，如果你有需求，后续的更新中我可以添加。
第二个问题，如果你的需求是让一个回复在你机器人的多个群内触发，那么可以设置为全局触发
具体学习方法可以参考我插件的文档，或者类似于下


学习 触发内容&nbsp; 回复内容&nbsp; 全局


在结尾出添加&nbsp; 全局&nbsp; 参数，就可以将本条消息设置为所有机器人在的群都会触发该条信息的回复。


如有其他问题或者意见，可以在插件帖下面留言或者加我qq572490972


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Moyuyanli/HuYanSession"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月27日(星期一) 下午2:49
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Moyuyanli/HuYanSession] 几个疑问想请教 (Issue #1)





 
作者你好，该插件能不能实现
 1.发送聊天记录，类似于下图
 
 2.可不可以将学习的东西应用在多个群中（给群分组，给这个组的机器人相同配置
 原因：将机器人放在学校的几个新生群做答疑用，Q群管家有要修改的话需要一个一个群改

**Comment by MokouTyan** [comment]
感谢开发～

全局可能会有点哈人（毕竟bot还放在几个游戏群、涩图群中）所以还是期待一下有群分组功能

这样子就可以一次配置数据，适用于多个群了～

**Comment by Moyuyanli** [comment]
我会将这几点添加到插件规划当中，请关注后期更新。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Moyuyanli/HuYanSession"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月27日(星期一) 下午3:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Moyuyanli/HuYanSession] 几个疑问想请教 (Issue #1)





 
感谢开发～
 
全局可能会有点哈人（毕竟bot还放在几个游戏群、涩图群中）所以还是期待一下有群分组功能
 
这样子就可以一次配置数据，适用于多个群了～

**Comment by damemod** [comment]
实际上，可以添加一个针对群个人的词库，这么可以更好的DIY,同时这也灵活开放一部分权限。

**Comment by Moyuyanli** [comment]
> 实际上，可以添加一个针对群个人的词库，这么可以更好的DIY,同时这也灵活开放一部分权限。

不是很明白你的意思

**Comment by damemod** [comment]
对群里的个人如(qq)为对象而不是整个群成员

**Comment by damemod** [comment]
可以参考一下
![image](https://user-images.githubusercontent.com/85817502/187064919-65fadf2c-7c62-4831-be65-8644a49e5bff.png)

**Comment by Moyuyanli** [comment]
> 对群里的个人如(qq)为对象而不是整个群成员

这样的话就得新建一个表来存指定群成员的信息，造成更多的数据，另外如果说我要指定多个人，还得再建一个list。
业务场景不是很实用

**Comment by Moyuyanli** [comment]
> 可以参考一下 ![image](https://user-images.githubusercontent.com/85817502/187064919-65fadf2c-7c62-4831-be65-8644a49e5bff.png)

这个可以考虑做成一个偏娱乐性的插件，我后续会出一个跟经济有关的插件，做成这个插件的功能吧。
另外，在壶言2的规划中，触发词可以为正则表达式，目前还没实现

**Comment by damemod** [comment]
敬请期待，希望壶言2会越来越好

**Comment by Moyuyanli** [comment]
> 敬请期待，希望壶言2会越来越好

谢谢
