### ISSUE TITLE
语音故障

### ISSUE THREAD

**Issue by linux-rm** [Moyuyanli/HuYanSession#10]
问题很奇怪，日志没有出现错误，跟正常的语音是一样的

![聊天记录](https://user-images.githubusercontent.com/100938047/195993600-e1be0d28-a2c1-48fe-834b-87d1d60a4c6b.png)

![查询](https://user-images.githubusercontent.com/100938047/195993712-116ba15c-c092-42b7-960b-3de00f735f59.jpg)

**Comment by Moyuyanli** [comment]
这个好像是qq那边过期了
