### ISSUE TITLE
图片问题

### ISSUE THREAD

**Issue by linux-rm** [Moyuyanli/HuYanSession#14]
机器人在回复图片时

手机(Android)显示图片过期或损坏

电脑(Linux)直接不显示

包括所有群友也都说图片出错

终端没有任何报错

**Comment by Moyuyanli** [comment]
等一手2.4.0改为本地缓存图片，保证永不丢失

**Comment by Moyuyanli** [comment]
已解决，目前只有%xx启用，需要在配置中开启本地缓存
