### ISSUE TITLE
提出一些bug

### ISSUE THREAD

**Issue by damemod** [Moyuyanli/HuYanSession#2]
添加多词条时对结束语句也进行了回复

禁言群主时，显示两条相反的信息

**Comment by Moyuyanli** [comment]
这是壶言1吧？具体我问题我去看看

**Comment by Moyuyanli** [comment]
可以提供一下报错信息吗？

**Comment by damemod** [comment]
并没有报错信息

> 可以提供一下报错信息吗？

**Comment by damemod** [comment]
> 可以提供一下报错信息吗？

当时没出现报错，我重新复现了一下

**Comment by Moyuyanli** [comment]
> > 可以提供一下报错信息吗？
> 
> 抱歉，当时没出现报错，我重新复现了一下

我已经在寻找问题了，谢谢提交

**Comment by damemod** [comment]
[新建 文本文档.txt](https://github.com/Moyuyanli/HuYanSession/files/9439337/default.txt)

**Comment by Moyuyanli** [comment]
多词条问题已经修复
