### ISSUE TITLE
视频学习故障

### ISSUE THREAD

**Issue by linux-rm** [Moyuyanli/HuYanSession#8]
![聊天](https://user-images.githubusercontent.com/100938047/193429598-efca5f05-2924-4c49-8e92-bf457c089184.png)
包括文件也不能学习

**Comment by Moyuyanli** [comment]
![图片](https://user-images.githubusercontent.com/79217875/194694300-89e7b910-8372-4f10-9da6-cfe5d773bf26.png)
![图片](https://user-images.githubusercontent.com/79217875/194694316-d4d01035-304b-4574-98c8-67668b7617d5.png)
视频消息目前好像还不支持，文件消息不支持转发，要实现也行，但是比较麻烦，如果你有需求的话，我将文件发送添加到历程里面。
